Add files via upload
kit-cpp-course/myasnikov-iv pull request #1
Opened 2018-12-22 03:15 UTC by Ektaros

2018-12-24 22:20 UTC, alpatov requested changes
Нужно описать процесс анализа и каталогизации в объектно-ориентированном стиле.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/FileSystemTools.h
> +		// �������� �� ������������� ����� ��� �����
Комментарии не читаются.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/FileSystemTools.h
> +	class FileSystemTools {
Документацию следует добавлять не только к компонентам класса, но и к самому классу.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/ImgPoint.h
> +	//���������� ������ ���������� ��������� ����� EXIFInfo ��� ��������� ������ �� ����������
Комментарии не читаются 👎

2018-12-24 22:20 UTC, alpatov commented on CourseWork/ImgPoint.h
> +	ImgPoint(std::string path): path(path){
Такие методы (тем более конструкторы) не стоит описывать при объявлении. Их описание нужно выносить за пределы класса. Желательно делать это в cpp-файле.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/Point.h
> +class Point {
Насколько я понимаю, у нас речь идёт о гео-данных. Поэтому лучше не описывать гео-точку, в терминах декартовой системы координат, поскольку это вносит двусмысленность. Лучше пользоваться терминами: широта и долгота.

Не уверен, какую систему геопозиционирования Вы используете (поскольку не могу прочитать комментарии), но в системе GPS, координаты описываются в пределах точности типа данных double.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/arguments.h
> +	class arguments {
Документация???

2018-12-24 22:20 UTC, alpatov commented on CourseWork/arguments.h
> +		bool isKey(size_t index) const {
Описание методов лучше вынести в cpp-файл.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/configs.h
> +class config {
Документация???

2018-12-24 22:20 UTC, alpatov commented on CourseWork/fileSystemTools.cpp
> +bool FileSystemTools::createFolder(wstring* const path)
Можно увеличить модульность за счёт создания вспомогательных методов.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/fileSystemTools.cpp
> +		if (error == ERROR_FILE_EXISTS) {
Конструкция if избыточна. Достаточно возвращать условие, которое Вы поместили в заголовок if.

А, если подумать ещё немного, можно избавиться и от if-а, который выше :)

2018-12-24 22:20 UTC, alpatov commented on CourseWork/fileSystemTools.cpp
> +		if (n > 4)
Вложенный if - не нужен, можно заменить логическим оператором.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/fileSystemTools.cpp
> +		if (n > 4)
Если мы используем вложенные друг в друга конструкции, следует ставить фигурные скобки.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/main.cpp
> +	zones[0] =new Zone("St.Petersburg", Point(59.784857f, 29.939072f), Point(60.1059280f, 30.6244484f));
Зоны нужно хранить в файле и загружать из него.

2018-12-24 22:20 UTC, alpatov commented on CourseWork/main.cpp
> +	string pathToData = cfg.input();
Процесс каталогизации должен быть представлен в виде класса. А лучше нескольких. Поскольку каталогизация - это процесс поиска, в результате, которого получается объектная модель (система связанных объектов), и последующий процесс преобразования полученной модели и её сохранения в виде элемента структуры файловой системы.

2018-12-25 04:02 UTC, Ektaros commented on CourseWork/fileSystemTools.cpp
> +bool FileSystemTools::createFolder(wstring* const path)
Можно тут небольшую подсказку? Немного не понимаю что вы предлагаете вынести.

2018-12-26 22:56 UTC, closed without merging